language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
services:
  - postgresql
addons:
  postgresql: "9.6"
global:
  - PGPORT=5432
before_script:
 - cp local_settings.travis.py local_settings.py
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - psql -U postgres -c "ALTER USER decide CREATEDB"
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
- pip install codacy-coverage
script: 
- python manage.py test
- coverage xml
- python-codacy-coverage -r coverage.xml
if: branch=master
deploy:
  provider: heroku
  app: egc-1819-edubotdom-1530
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
   branch: master